modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/ModdingPlus/CompassPlus/issues"
license="Unlicense"

[[mods]]
modId="compass_plus"
version="${file.jarVersion}"
displayName="Compass Plus"
updateJSONURL="https://gist.githubusercontent.com/QbDesu/22a14ea04a63b0b1fe1484c46fb6786a/raw/compass_plus_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/compass_plus"
logoFile="compass_plus.png"
credits="Thanks to helpful people in the Forge and MMD Discord servers."

authors="Qb"
description='''
A fancy hud for your compass!
'''

[[dependencies.compass_plus]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.compass_plus]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"